[selene]
base = "lua51"
name = "luasnip"

[s]
any = true
[sn]
any = true
[t]
any = true
[f]
any = true
[i]
any = true
[c]
any = true
[d]
any = true
[r]
any = true
[l]
any = true
[rep]
any = true
[p]
any = true
[m]
any = true
[n]
any = true
[dl]
any = true
[fmt]
any = true
[fmta]
any = true
[conds]
any = true
[types]
any = true
[events]
any = true
[parse]
any = true
[ai]
any = true
[postfix]
any = true
